### ISSUE TITLE
--hostname=<hostname>: not found

### ISSUE THREAD

**Issue by schildbach** [mikehearn/httpseed#4]
Regardless of the --hostname parameter, I always get the above error message.

I think Cartographer should be able to run without the parameter. Servers usually know their hostname.

**Comment by mikehearn** [comment]
I'm not sure what the best way to find the external hostname is. I've certainly had VPS' that didn't know what they were mapped to in DNS.

**Comment by schildbach** [comment]
Reverse lookup of the IP address?

What do we even need the hostname for? In the end, we only need IP addresses, right?

**Comment by mikehearn** [comment]
It's put into the subVer field of the version message so people know which crawler is crawling them. I think it may be used in the DNS code too, can't quite remember.

**Comment by schildbach** [comment]
Yeah but the version message stuff can be optional (not everyone will want that) and DNS resolves to IP addresses, not hostnames.

**Comment by mikehearn** [comment]
I think it's good to ask users to identify themselves when crawling the network. It makes it easier to find people who are crawling too aggressively. And IMO it's just no big deal: one command line switch ? What's the issue?

**Comment by schildbach** [comment]
Well the issue is the switch doesn't work (-:
